global using Carter;
global using MediatR;
global using Mapster;
global using NexiusTestTodo.API.Models;
global using NexiusTestTodo.Domain;
global using NexiusTestTodo.Data.Repositories;
global using NexiusTestTodo.Data.Interfaces;
global using FluentValidation;
global using NexiusTestTodo.API.Validation;